spring.application.name=file-vault

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/filevault
spring.datasource.username=filevaultuser
spring.datasource.password=3027
spring.datasource.driverClassName=org.postgresql.Driver

# JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT configuration
jwt.secret=${JWT_SECRET}
jwt.expiration={$JWT_EXPIRATION:86400000}

# Ollama API configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2
spring.ai.ollama.embedding.model=nomic-embed-text

# PGVector configuration
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.initialize-schema=true